---
- name: Replicazione Infrastruttura Terraform su OpenStack
  hosts: localhost
  connection: local
  vars:
    key_name: "key_test"
    bastion_ip: "/32" # ip Bastion
    controller_ip: "" # private ip ansible machine
    image_name: "Rocky-9-GenericCloud.latest.x86_64.310525"

  tasks:
    # Security Group SSH
    - name: Crea Security Group SSH Internal
      openstack.cloud.security_group:
        cloud: openstack_recas
        name: "ssh-internal"
        description: "[ansible] Allow SSH from Bastion"
        state: present
        register: security_group

    - name: Ispezione completa output del security group
      ansible.builtin.debug:
        var: security_group

    # Istanza Compute
    - name: Launch PostgreSQL VM
      openstack.cloud.server:
        cloud: openstack_recas
        name: "postgresql-backend"
        image: "{{ image_name }}"
        flavor: "medium"  
        key_name: ""
        security_groups:
          - default
          - ssh-internal
        network: "private_net"
        userdata: "{{ lookup('template', 'cloudinit.sh.j2') }}"
      register: psql_vm

    - name: Ispezione completa output della VM
      ansible.builtin.debug:
        var: psql_vm
        
    # Output (output "psql_vm_private_ip")
    - name: shows private IP 
      debug:
        msg: "The private IP is: {{ psql_vm.server.addresses.private_net[0].addr }}"
